### ISSUE TITLE
GitLabForm v5 fails to unprotect branch on Gitlab CE 18.8

### ISSUE THREAD

**Issue by aveyrenc** [gitlabform/gitlabform#1193]
**Describe the bug**

When trying to unprotect the main branch to create a new release, with the following GitLabForm configuration:

```yaml
config_version: 4
gitlab:
  url: https://gitlab.my.domain/
projects_and_groups:
  path/to/my/project:
    branches:
      main:
        protected: true
        allow_force_push: false
        push_access_level: maintainer
        code_owner_approval_required: false
```

It fails with the following error:

```
🏗 GitLabForm version: 5.0.0 Warning: Connected as non-admin. You may encounter permission issues.
>>> Getting requested groups or projects...
:: # of groups to process: 0
:: # of projects to process: 1
* (1/1) Processing project: path/to/my/project
Warning: Error occurred while processing project path/to/my/project, exception:
'ProjectProtectedBranch' object has no attribute 'unprotect_access_levels'
:: # of groups processed successfully: 0
:: # of projects processed successfully: 0
:: # of projects failed: 1 
:: Failed project 1: path/to/my/project
```

**GitLabForm version**

🏗 GitLabForm version: 5.0.0 = the latest stable 😊

**GitLab version**

`18.8.5-ce`

**Comment by aveyrenc** [comment]
Hello

Here is the configuration that we're currently using and that works with version 4.8:

```yaml
config_version: 3
gitlab:
  url: https://gitlab.my.domain/
projects_and_groups:
  path/to/my/project:
    branches:
      main:
        protected: true
        push_access_level: maintainer
```

@amimas When I say unprotect, it's because in this configuration we allow push access to maintainers. At the end of the CI pipeline, we have an opposite task that "protects" the branch, switching `push_access_level` to `no access`

**Comment by oupala** [comment]
I have the same error message with Framagit (GitLab v18.9.2) and with the following yaml:

```yaml
    branches:
      main:
        protected: true
        push_access_level: maintainer
        merge_access_level: developer
        unprotect_access_level: maintainer
        allow_force_push: false
```

**Comment by amimas** [comment]
Thanks @TimKnight01 . I was also trying that out too and have same findings.

`GET` the `main` branch's protection config:

```bash
$ curl -s -H "Authorization:Bearer $(cat gitlab_token.txt)" ${GITLAB_API_URL}/projects/1/protected_branches/main | jq

{
  "id": 1,
  "name": "main",
  "push_access_levels": [
    {
      "id": 1,
      "access_level": 40,
      "access_level_description": "Maintainers",
      "deploy_key_id": null
    }
  ],
  "merge_access_levels": [
    {
      "id": 1,
      "access_level": 40,
      "access_level_description": "Maintainers"
    }
  ],
  "allow_force_push": true
}
```

`PATCH` to update the existing `push_access_levels` config:

```bash
$ curl -s --request PATCH -H "Content-Type: application/json" -H "Authorization:Bearer $(cat gitlab_token.txt)" --url "${GITLAB_API_URL}/projects/1/protected_branches/main" --data '{"allowed_to_push": [{"id": 1, "access_level": 0}]}' | jq


{
  "id": 1,
  "name": "main",
  "push_access_levels": [
    {
      "id": 1,
      "access_level": 40,
      "access_level_description": "Maintainers",
      "deploy_key_id": null
    }
  ],
  "merge_access_levels": [
    {
      "id": 1,
      "access_level": 40,
      "access_level_description": "Maintainers"
    }
  ],
  "allow_force_push": true
}
```

The API does not return any errors and it also does not update the config. So I agree that for CE edition of GitLab, we can just use the previous workflow of unprotecting the branch and then reprotect it again. Too bad the API and different editions of GitLab is not consistent.
